name: Artifacts Demo

on:
  push:
    branches:
      - master

jobs:
  generate-artifact:
    name: Generate and Upload Artifact
    runs-on: windows-latest

    steps:
      - name: Create a Sample File
        run: echo Hello, this is a log file from GitHub Actions! > my_log.txt

      - name: Upload the Artifact with retention
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: my_log.txt
          retention-days: 5  

      - name: Create a Sample File 1
        run: echo Hello, this is a first log file from GitHub Actions! > my_log1.txt

      - name: Upload the 2nd Artifact with retention
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact1 
          path: my_log1.txt
          retention-days: 1

  download-artifact:
    name: Download and Use Artifact
    runs-on: windows-latest  
    needs: generate-artifact

    steps:
      - name: Download the Artifact
        uses: actions/download-artifact@v4
        with:
          name: my-artifact

      - name: Download the 2nd Artifact file
        uses: actions/download-artifact@v4
        with:
          name: my-artifact1  

      - name: Display Artifact Content
        run: type my_log.txt 

      - name: Display Artifact 1 Content
        run: type my_log1.txt
