name: Manual Trigger with Inputs
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select the deployment environment"
        required: true
        default: "staging"
        type: choice
        options:
          - Development
          - Testing
          - Deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Print Selected Environment
        run: echo "Deploying to ${{ github.event.inputs.environment }}"
