name: Matrix Jobs Demo

on:
  push:
    branches:
      - master

jobs:
  test-matrix:
    name: Run on Multiple OS
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Print OS Info
        run: |
          echo "Running on ${{ matrix.os }}"
          uname -a || systeminfo
