name: Advanced Workflow

on:  
  push:
    branches:
      - master  # Run when pushing to the main branch
  pull_request:
    branches:
      - master  # Run on pull requests targeting main

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu for execution

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Get the code from GitHub

      - name: Print the Current Directory
        run: pwd  # Show the working directory

      - name: List Files in Repo
        run: ls -l  # Show all files

      - name: Print Hello with Date
        run: echo "Hello, GitHub Actions! Today is $(date)"

      - name: new step
        run: echo "Workflow is running successfully"

      - name: GitHub username
        run: echo "User: ${{github.actor}}"
