name: Runner Demo

on:  
  push:
    branches:
      - master

jobs:
  ubuntu-job:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Print OS Info
        run: cat /etc/os-release

  windows-job:
    name: Run on Windows
    runs-on: windows-latest
    steps:
      - name: Print OS Info
        run: systeminfo

  macos-job:
    name: Run on macOS
    runs-on: macos-latest
    steps:
      - name: Print OS Info
        run: uname -a
