name: Trigger Workflow Demo

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:  # Allows manual trigger from GitHub Actions UI
  schedule:
    - cron: "0 5 * * *"  # Runs daily at 5 AM UTC

jobs:
  check-trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Print Trigger Information
        run: echo "Triggered by owner"

      - name: Print Committer Name (if push)
        if: ${{ github.event_name == 'push' }}
        run: echo "Commit made by owner"

      - name: Print Pull Request Info (if PR)
        if: ${{ github.event_name == 'pull_request' }}
        run: echo "Pull request by owner"
