name: Python Matrix Jobs

on:
  push:
    branches:
      - master

jobs:
  test-python:
    name: Test on Multiple Python Versions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11.11, 3.13.1, 3.12.8, 3.12.9, 3.13.2]

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Print Python Version
        run: python --version

  test-os:
    name: Run on Multiple OS
    runs-on: ${{ matrix.os }}
    needs: test-python
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Print OS Info
        run: |
          echo "Running on ${{ matrix.os }}"
          uname -a || systeminfo
