name: Cache Demo

on:
  push:
    branches:
      - master

jobs:
  cache-example:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Python Application
        run: python app.py

      - name: Run Flask App
        run: python app.py &

      - name: Wait for 30 seconds
        run: sleep 30

      - name: Stop Flask App
        run: pkill -f "python app.py"
