name: Advanced Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Print the Current Directory
        run: pwd
      - name: List Files in Repo
        run: ls -l
      - name: Print Hello with Date
        run: echo "Hello, GitHub Actions! Today is $(date)"
      - name: new step
        run: echo "Workflow is running successfully"
