name: Custom Action Demo
on:
  push:
    branches:
      - master

jobs:
  run-custom-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Use Custom Action
        uses: ./custom-action 
        with:
          username: "Owner"

