name: Env and Secrets Demo

on:
  workflow_dispatch:

jobs:
  demo-job:
    runs-on: ubuntu-latest
    env:
      APP_NAME: "My GitHub Actions App"
    steps:
      - name: Display Environment Variables
        run: |
          echo "App Name: $APP_NAME"
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref }}"

      - name: Access a Secret
        run: echo "The secret greeting is ${{ secrets.GREETING }}"
