name: JavaScript Action Demo

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  run-js-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Use JavaScript Action
        uses: ./js-action 
        with:
          username: "Owner"
