name: JavaScript Action Demo

on:
  push:
    branches:
      - master
  workflow_dispatch: 

jobs:
  run-js-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 
      - name: Install Dependencies
        run: |
          cd js-action
          npm install 

      - name: Use JavaScript Action
        uses: ./js-action 
        with:
          username: "Prathamesh"
